// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Shadow> {
    public static var card: Self { .init(keyPath: \.shadows.card) }
}

nonisolated extension ShapeStyle {
    public var card: ThemeShadowedStyle<Self> { .init(base: self, shadowKeyPath: \.shadows.card) }
}
