// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Color> {
    public static var surface: Self { .init(keyPath: \.colors.surface) }
    public static var onSurface: Self { .init(keyPath: \.colors.onSurface) }
    public static var icon: Self { .init(keyPath: \.colors.icon) }
}
