// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated extension ShapeStyle where Self == ThemeShapeStyle<MeshGradient> {
    public static var primaryBackground: Self { .init(keyPath: \.meshGradients.primaryBackground) }
}
