// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Gradient> {
    public static var primaryGradient: Self { .init(keyPath: \.gradients.primaryGradient) }
}
