// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeShapeStyle<Style: ShapeStyle & Sendable & Codable & Equatable>: ShapeStyle, Equatable {
    nonisolated let keyPath: KeyPath<Theme, ThemeAdaptiveStyle<Style>>

    nonisolated public init(keyPath: KeyPath<Theme, ThemeAdaptiveStyle<Style>>) {
        self.keyPath = keyPath
    }

    nonisolated public func resolve(in environment: EnvironmentValues) -> some ShapeStyle {
        environment.theme[keyPath: keyPath].resolved(in: environment)
    }
}
