// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeGradients: Sendable, Codable, Equatable {
    public let primaryGradient: ThemeAdaptiveStyle<Gradient>

    nonisolated public init(
        primaryGradient: ThemeAdaptiveStyle<Gradient>
    ) {
        self.primaryGradient = primaryGradient
    }
}
