// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

extension ThemeShadows {
    nonisolated public func copyWith(
        card: ThemeAdaptiveStyle<Shadow>? = nil
    ) -> ThemeShadows {
        ThemeShadows(
            card: card ?? self.card
        )
    }
}
