// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

extension ThemeColors {
    nonisolated public func copyWith(
        surface: ThemeAdaptiveStyle<Color>? = nil,
        onSurface: ThemeAdaptiveStyle<Color>? = nil,
        icon: ThemeAdaptiveStyle<Color>? = nil
    ) -> ThemeColors {
        ThemeColors(
            surface: surface ?? self.surface,
            onSurface: onSurface ?? self.onSurface,
            icon: icon ?? self.icon
        )
    }
}
