// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

extension ThemeGradients {
    nonisolated public func copyWith(
        primaryGradient: ThemeAdaptiveStyle<Gradient>? = nil
    ) -> ThemeGradients {
        ThemeGradients(
            primaryGradient: primaryGradient ?? self.primaryGradient
        )
    }
}
