// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct Theme: Sendable, Codable, Equatable {
    public let colors: ThemeColors
    public let gradients: ThemeGradients
    public let meshGradients: ThemeMeshGradients
    public let shadows: ThemeShadows

    nonisolated public init(
        colors: ThemeColors,
        gradients: ThemeGradients,
        meshGradients: ThemeMeshGradients,
        shadows: ThemeShadows
    ) {
        self.colors = colors
        self.gradients = gradients
        self.meshGradients = meshGradients
        self.shadows = shadows
    }
}
