// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeShadows: Sendable, Codable, Equatable {
    public let card: ThemeAdaptiveStyle<Shadow>

    nonisolated public init(
        card: ThemeAdaptiveStyle<Shadow>
    ) {
        self.card = card
    }
}
