// Generated by ThemeKit — do not edit

import SwiftUI

nonisolated private struct ThemeEnvironmentKey: EnvironmentKey {
    static let defaultValue: Theme = .default
}

nonisolated extension EnvironmentValues {
    public var theme: Theme {
        get { self[ThemeEnvironmentKey.self] }
        set { self[ThemeEnvironmentKey.self] = newValue }
    }
}
