// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

#if !os(Android)
nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Shadow> {
    public static var card: Self { .init(keyPath: \.shadows.card) }
    public static var raised: Self { .init(keyPath: \.shadows.raised) }
}

nonisolated extension ShapeStyle {
    public var card: ThemeShadowedStyle<Self> { .init(base: self, shadowKeyPath: \.shadows.card) }
    public var raised: ThemeShadowedStyle<Self> { .init(base: self, shadowKeyPath: \.shadows.raised) }
}
#else
nonisolated extension AndroidShapeStyleAdapter where Self == ThemeShapeStyle<Shadow> {
    public static var card: Self { .init(keyPath: \.shadows.card) }
    public static var raised: Self { .init(keyPath: \.shadows.raised) }
}

nonisolated extension AndroidShapeStyleAdapter {
    public var card: ThemeShadowedStyle<Self> { .init(base: self, shadowKeyPath: \.shadows.card) }
    public var raised: ThemeShadowedStyle<Self> { .init(base: self, shadowKeyPath: \.shadows.raised) }
}
#endif
