// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

#if !os(Android)
nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Gradient> {
    public static var primaryGradient: Self { .init(keyPath: \.gradients.primaryGradient) }
    public static var sunsetGradient: Self { .init(keyPath: \.gradients.sunsetGradient) }
}
#else
nonisolated extension AndroidShapeStyleAdapter where Self == ThemeShapeStyle<Gradient> {
    public static var primaryGradient: Self { .init(keyPath: \.gradients.primaryGradient) }
    public static var sunsetGradient: Self { .init(keyPath: \.gradients.sunsetGradient) }
}
#endif
