// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

#if !os(Android)
nonisolated extension ShapeStyle where Self == ThemeShapeStyle<MeshGradient> {
    public static var primaryBackground: Self { .init(keyPath: \.meshGradients.primaryBackground) }
}
#else
nonisolated extension AndroidShapeStyleAdapter where Self == ThemeShapeStyle<MeshGradient> {
    public static var primaryBackground: Self { .init(keyPath: \.meshGradients.primaryBackground) }
}
#endif
