// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

#if !os(Android)
nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Color> {
    public static var surface: Self { .init(keyPath: \.colors.surface) }
    public static var cardSurface: Self { .init(keyPath: \.colors.cardSurface) }
    public static var onSurface: Self { .init(keyPath: \.colors.onSurface) }
    public static var icon: Self { .init(keyPath: \.colors.icon) }
    public static var primaryColor: Self { .init(keyPath: \.colors.primary) }
}
#else
nonisolated extension AndroidShapeStyleAdapter where Self == ThemeShapeStyle<Color> {
    public static var surface: Self { .init(keyPath: \.colors.surface) }
    public static var cardSurface: Self { .init(keyPath: \.colors.cardSurface) }
    public static var onSurface: Self { .init(keyPath: \.colors.onSurface) }
    public static var icon: Self { .init(keyPath: \.colors.icon) }
    public static var primaryColor: Self { .init(keyPath: \.colors.primary) }
}
#endif
