// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeColors: Sendable, Codable, Equatable {
    public let surface: ThemeAdaptiveStyle<Color>
    public let onSurface: ThemeAdaptiveStyle<Color>
    public let icon: ThemeAdaptiveStyle<Color>
    public let accent: ThemeAdaptiveStyle<Color>

    nonisolated public init(
        surface: ThemeAdaptiveStyle<Color>,
        onSurface: ThemeAdaptiveStyle<Color>,
        icon: ThemeAdaptiveStyle<Color>,
        accent: ThemeAdaptiveStyle<Color>
    ) {
        self.surface = surface
        self.onSurface = onSurface
        self.icon = icon
        self.accent = accent
    }
}
