// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

// #Preview macro is not available in SkipFuseUI on Android.
#if !os(Android)
/// A SwiftUI view that renders all theme tokens as a visual palette.
public struct ThemePreview: View {

    public var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                // MARK: - Colors
                VStack(alignment: .leading, spacing: 12) {
                    Text("Colors")
                        .font(.headline)
                    LazyVGrid(columns: [GridItem(.adaptive(minimum: 96))], spacing: 12) {
                            ColorSwatch(name: "surface", style: .surface)
                            ColorSwatch(name: "onSurface", style: .onSurface)
                            ColorSwatch(name: "icon", style: .icon)
                            ColorSwatch(name: "primary", style: .primaryColor)
                    }
                }
                // MARK: - Gradients
                VStack(alignment: .leading, spacing: 12) {
                    Text("Gradients")
                        .font(.headline)
                    LazyVGrid(columns: [GridItem(.adaptive(minimum: 96))], spacing: 12) {
                            GradientStrip(name: "primaryGradient", style: .primaryGradient)
                            GradientStrip(name: "sunsetGradient", style: .sunsetGradient)
                    }
                }
                // MARK: - Mesh Gradients
                VStack(alignment: .leading, spacing: 12) {
                    Text("Mesh Gradients")
                        .font(.headline)
                    LazyVGrid(columns: [GridItem(.adaptive(minimum: 120))], spacing: 12) {
                            MeshGradientCard(name: "primaryBackground", style: .primaryBackground)
                    }
                }
                // MARK: - Shadows
                VStack(alignment: .leading, spacing: 12) {
                    Text("Shadows")
                        .font(.headline)
                    LazyVGrid(columns: [GridItem(.adaptive(minimum: 60))], spacing: 12) {
                        ShadowCard(name: "card", style: .background.card)
                        ShadowCard(name: "raised", style: .background.raised)
                    }
                }
            }
            .padding()
        }
    }
}

#Preview {
    ThemePreview()
}

// MARK: - Preview Components

private struct ColorSwatch<Style: ShapeStyle>: View {
    let name: String
    let style: Style

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 8)
                .fill(style)
                .frame(height: 32)

            Text(name)
                .font(.caption)
                .lineLimit(1)
                .foregroundStyle(.secondary)
        }
    }
}

private struct GradientStrip<Style: ShapeStyle>: View {
    let name: String
    let style: Style

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 8)
                .fill(style)
                .frame(height: 48)

            Text(name)
                .font(.caption)
                .lineLimit(1)
                .foregroundStyle(.secondary)
        }
    }
}

private struct MeshGradientCard<Style: ShapeStyle>: View {
    let name: String
    let style: Style

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 12)
                .fill(style)
                .frame(height: 96)

            Text(name)
                .font(.caption)
                .lineLimit(1)
                .foregroundStyle(.secondary)
        }
    }
}

private struct ShadowCard<Style: ShapeStyle>: View {
    let name: String
    let style: Style

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 12)
                .fill(style)
                .frame(height: 60)

            Text(name)
                .font(.caption)
                .lineLimit(1)
                .foregroundStyle(.secondary)
        }
    }
}
#endif
