// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeGradients: Sendable, Codable, Equatable {
    public let primaryGradient: ThemeAdaptiveStyle<Gradient>
    public let sunsetGradient: ThemeAdaptiveStyle<Gradient>

    nonisolated public init(
        primaryGradient: ThemeAdaptiveStyle<Gradient>,
        sunsetGradient: ThemeAdaptiveStyle<Gradient>
    ) {
        self.primaryGradient = primaryGradient
        self.sunsetGradient = sunsetGradient
    }
}
