// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeShapeStyle<Style: Sendable & Codable & Equatable>: Equatable, Sendable {
    nonisolated let keyPath: KeyPath<Theme, ThemeAdaptiveStyle<Style>>

    nonisolated public init(keyPath: KeyPath<Theme, ThemeAdaptiveStyle<Style>>) {
        self.keyPath = keyPath
    }
}

#if !os(Android)
nonisolated extension ThemeShapeStyle: ShapeStyle where Style: ShapeStyle {
    nonisolated public func resolve(in environment: EnvironmentValues) -> some ShapeStyle {
        environment.theme[keyPath: keyPath].resolved(in: environment)
    }
}
#endif
