// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeMeshGradients: Sendable, Codable, Equatable {
    public let primaryBackground: ThemeAdaptiveStyle<MeshGradient>

    nonisolated public init(
        primaryBackground: ThemeAdaptiveStyle<MeshGradient>
    ) {
        self.primaryBackground = primaryBackground
    }
}
