// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeShadows: Sendable, Codable, Equatable {
    public let card: ThemeAdaptiveStyle<Shadow>
    public let raised: ThemeAdaptiveStyle<Shadow>

    nonisolated public init(
        card: ThemeAdaptiveStyle<Shadow>,
        raised: ThemeAdaptiveStyle<Shadow>
    ) {
        self.card = card
        self.raised = raised
    }
}
