// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeShadowedStyle<Base: Sendable>: Sendable {
    nonisolated let base: Base
    nonisolated let shadowKeyPath: KeyPath<Theme, ThemeAdaptiveStyle<Shadow>>

    nonisolated public init(base: Base, shadowKeyPath: KeyPath<Theme, ThemeAdaptiveStyle<Shadow>>) {
        self.base = base
        self.shadowKeyPath = shadowKeyPath
    }
}

extension ThemeShadowedStyle: Equatable where Base: Equatable {}

// ShadowStyle and ShapeStyle conformance with custom resolve() are not available in
// SkipFuseUI on Android; there the shadow is applied as a view modifier instead, by the
// overloads in View+ThemeStyles.swift.
#if !os(Android)
nonisolated extension ThemeShadowedStyle: ShapeStyle where Base: ShapeStyle {
    nonisolated public func resolve(in environment: EnvironmentValues) -> some ShapeStyle {
        let shadow = environment.theme[keyPath: shadowKeyPath]
            .resolved(in: environment)
        guard let shadowStyle = shadow.shadowStyle else {
            return AnyShapeStyle(base)
        }
        return AnyShapeStyle(base.shadow(shadowStyle))
    }
}
#endif
