// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

// Sendable is stated unconditionally: on Apple the conditional ShapeStyle conformance
// below inherits Sendable, and an inherited protocol is not implied by a conditional
// conformance, so it has to be satisfied up front.
nonisolated public struct ThemeShapeStyle<Style: Sendable & Codable & Equatable>: Equatable, Sendable {
    nonisolated let keyPath: KeyPath<Theme, ThemeAdaptiveStyle<Style>>

    nonisolated public init(keyPath: KeyPath<Theme, ThemeAdaptiveStyle<Style>>) {
        self.keyPath = keyPath
    }
}

// ShapeStyle conformance with custom resolve() is not available in SkipFuseUI on Android;
// there the generated modifier overloads in View+ThemeStyles.swift render tokens instead.
//
// The same rule as the Sendable note above is why this type is not the one bridged to
// Compose in native mode: on Android ShapeStyle inherits SkipUIBridging, JConvertible and
// JObjectProtocol, and a conditional conformance would have to restate every one of them —
// names that live in swift-jni, which an app target has no reason to depend on. The
// accessors hand Compose an AnyShapeStyle instead.
#if !os(Android)
nonisolated extension ThemeShapeStyle: ShapeStyle where Style: ShapeStyle {
    nonisolated public func resolve(in environment: EnvironmentValues) -> some ShapeStyle {
        environment.theme[keyPath: keyPath].resolved(in: environment)
    }
}
#endif
