// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

extension ThemeMeshGradients {
    nonisolated public func copyWith(
        primaryBackground: ThemeAdaptiveStyle<MeshGradient>? = nil
    ) -> ThemeMeshGradients {
        ThemeMeshGradients(
            primaryBackground: primaryBackground ?? self.primaryBackground
        )
    }
}
