// Generated by ThemeKit — do not edit
//
// On Android ThemeShapeStyle is not a ShapeStyle — SkipFuseUI's ShapeStyle has no
// resolve(in:) customization point — so the style-taking modifiers are overloaded here
// over ThemeStyleResolving, which plays exactly the role ShapeStyle plays on Apple:
// the namespace the token accessors hang off, and the constraint that lets a chain like
// `.surface.cardShadow` re-bind from a style to a shadowed style.
//
// Only ThemeKit's own types conform to it. That is what keeps these overloads
// unambiguous with SkipFuseUI's `where S: ShapeStyle` modifiers — no type satisfies
// both constraints, so exactly one candidate ever applies to a given argument.

import SwiftUI
import ThemeKit

#if os(Android)

// MARK: - Resolution

// Sendable is required so `ThemeShadowedStyle<Self>` can be formed from any conformer.
nonisolated public protocol ThemeStyleResolving: Sendable {
    func themeRendering(
        theme: Theme,
        colorScheme: ColorScheme,
        sizeClass: UserInterfaceSizeClass?
    ) -> AndroidStyleRendering
}

nonisolated extension ThemeShapeStyle: ThemeStyleResolving where Style: AndroidRenderableStyle {
    nonisolated public func themeRendering(
        theme: Theme,
        colorScheme: ColorScheme,
        sizeClass: UserInterfaceSizeClass?
    ) -> AndroidStyleRendering {
        theme[keyPath: keyPath]
            .androidAdaptiveRendering(colorScheme: colorScheme, sizeClass: sizeClass)
    }
}

nonisolated extension ThemeShadowedStyle: ThemeStyleResolving where Base: ThemeStyleResolving {
    nonisolated public func themeRendering(
        theme: Theme,
        colorScheme: ColorScheme,
        sizeClass: UserInterfaceSizeClass?
    ) -> AndroidStyleRendering {
        let shadow = theme[keyPath: shadowKeyPath]
            .resolved(colorScheme: colorScheme, sizeClass: sizeClass)?
            .androidRendering.shadow
        return base.themeRendering(theme: theme, colorScheme: colorScheme, sizeClass: sizeClass)
            .adding(shadow)
    }
}

// MARK: - Wrapper views

/// Which modifier consumes the resolved style.
nonisolated public enum ThemeStyleTarget: Sendable {
    case foreground
    case background(ignoresSafeAreaEdges: Edge.Set)
    case border(width: CGFloat)
}

/// Applies a theme style to a view.
///
/// The theme has to be read inside a view body: SkipFuseUI has no environment at
/// bridging time, which is the whole reason this indirection exists. `@Environment`
/// properties are non-private because Skip requires that in shared views.
nonisolated struct ThemeStyledView<Content: View, Style: ThemeStyleResolving>: View {

    @Environment(\.theme) var theme: Theme
    @Environment(\.colorScheme) var colorScheme: ColorScheme
    @Environment(\.horizontalSizeClass) var sizeClass: UserInterfaceSizeClass?

    let style: Style
    let target: ThemeStyleTarget
    let content: Content

    var body: some View {
        let rendering = style.themeRendering(
            theme: theme, colorScheme: colorScheme, sizeClass: sizeClass
        )
        if let shadow = rendering.shadow {
            styled(rendering)
                .shadow(
                    color: shadow.color ?? Color(.sRGBLinear, white: 0, opacity: 0.33),
                    radius: shadow.radius,
                    x: shadow.x,
                    y: shadow.y
                )
        } else {
            styled(rendering)
        }
    }

    @ViewBuilder
    private func styled(_ rendering: AndroidStyleRendering) -> some View {
        if let shapeStyle = rendering.shapeStyle {
            switch target {
            case .foreground:
                content.foregroundStyle(shapeStyle)
            case .background(let edges):
                content.background(shapeStyle, ignoresSafeAreaEdges: edges)
            case .border(let width):
                content.border(shapeStyle, width: width)
            }
        } else {
            content
        }
    }
}

/// `background(_:in:)`, which needs the shape as well as the style.
nonisolated struct ThemeBackgroundShapeView<Content: View, Style: ThemeStyleResolving, ShapeType: Shape>: View {

    @Environment(\.theme) var theme: Theme
    @Environment(\.colorScheme) var colorScheme: ColorScheme
    @Environment(\.horizontalSizeClass) var sizeClass: UserInterfaceSizeClass?

    let style: Style
    let shape: ShapeType
    let fillStyle: FillStyle
    let content: Content

    var body: some View {
        let rendering = style.themeRendering(
            theme: theme, colorScheme: colorScheme, sizeClass: sizeClass
        )
        if let shapeStyle = rendering.shapeStyle {
            content.background(shapeStyle, in: shape, fillStyle: fillStyle)
        } else {
            content
        }
    }
}

/// Which shape operation consumes the resolved style.
nonisolated public enum ThemeShapeTarget: Sendable {
    case fill(FillStyle)
    case stroke(lineWidth: CGFloat)
}

/// `Shape.fill(_:)` and `Shape.stroke(_:lineWidth:)`.
nonisolated struct ThemeStyledShapeView<ShapeType: Shape, Style: ThemeStyleResolving>: View {

    @Environment(\.theme) var theme: Theme
    @Environment(\.colorScheme) var colorScheme: ColorScheme
    @Environment(\.horizontalSizeClass) var sizeClass: UserInterfaceSizeClass?

    let shape: ShapeType
    let style: Style
    let target: ThemeShapeTarget

    var body: some View {
        let rendering = style.themeRendering(
            theme: theme, colorScheme: colorScheme, sizeClass: sizeClass
        )
        if let shadow = rendering.shadow {
            filled(rendering)
                .shadow(
                    color: shadow.color ?? Color(.sRGBLinear, white: 0, opacity: 0.33),
                    radius: shadow.radius,
                    x: shadow.x,
                    y: shadow.y
                )
        } else {
            filled(rendering)
        }
    }

    @ViewBuilder
    private func filled(_ rendering: AndroidStyleRendering) -> some View {
        if let shapeStyle = rendering.shapeStyle {
            switch target {
            case .fill(let fillStyle):
                shape.fill(shapeStyle, style: fillStyle)
            case .stroke(let lineWidth):
                shape.stroke(shapeStyle, lineWidth: lineWidth)
            }
        } else {
            shape.fill(Color.clear)
        }
    }
}

// No `tint` overload is emitted. SwiftUI's `tint(_:)` takes an `S?`, and Swift cannot
// infer an implicit member's base through an optional generic — `.tint(.primaryColor)`
// does not compile on Apple. Emitting it on Android would create code that builds on one
// platform and not the other, which is precisely what this design exists to avoid.
// Use `.tint(theme.colors.primary.resolved(colorScheme:) ?? .accentColor)` on both.

// MARK: - Modifier overloads

nonisolated extension View {

    nonisolated public func foregroundStyle<S: ThemeStyleResolving>(_ style: S) -> some View {
        ThemeStyledView(style: style, target: .foreground, content: self)
    }

    nonisolated public func background<S: ThemeStyleResolving>(
        _ style: S,
        ignoresSafeAreaEdges edges: Edge.Set = []
    ) -> some View {
        ThemeStyledView(style: style, target: .background(ignoresSafeAreaEdges: edges), content: self)
    }

    nonisolated public func background<S: ThemeStyleResolving, T: Shape>(
        _ style: S,
        in shape: T,
        fillStyle: FillStyle = FillStyle()
    ) -> some View {
        ThemeBackgroundShapeView(style: style, shape: shape, fillStyle: fillStyle, content: self)
    }

    nonisolated public func border<S: ThemeStyleResolving>(
        _ style: S,
        width: CGFloat = 1
    ) -> some View {
        ThemeStyledView(style: style, target: .border(width: width), content: self)
    }
}

nonisolated extension Shape {

    nonisolated public func fill<S: ThemeStyleResolving>(
        _ style: S,
        style fillStyle: FillStyle = FillStyle()
    ) -> some View {
        ThemeStyledShapeView(shape: self, style: style, target: .fill(fillStyle))
    }

    nonisolated public func stroke<S: ThemeStyleResolving>(
        _ style: S,
        lineWidth: CGFloat = 1
    ) -> some View {
        ThemeStyledShapeView(shape: self, style: style, target: .stroke(lineWidth: lineWidth))
    }
}

#endif
