// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

#if os(Android)

// MARK: - Resolution

nonisolated public protocol AndroidShapeStyleAdapter: Sendable {
    func androidThemeRendering(
        theme: Theme,
        colorScheme: ColorScheme,
        sizeClass: UserInterfaceSizeClass?
    ) -> AndroidResolvedStyle
}

nonisolated extension ThemeShapeStyle: AndroidShapeStyleAdapter where Style: AndroidResolvableStyle {
    nonisolated public func androidThemeRendering(
        theme: Theme,
        colorScheme: ColorScheme,
        sizeClass: UserInterfaceSizeClass?
    ) -> AndroidResolvedStyle {
        theme[keyPath: keyPath]
            .resolved(colorScheme: colorScheme, sizeClass: sizeClass)?
            .androidResolvedStyle ?? .unsupported
    }
}

nonisolated extension ThemeShadowedStyle: AndroidShapeStyleAdapter where Base: AndroidShapeStyleAdapter {
    nonisolated public func androidThemeRendering(
        theme: Theme,
        colorScheme: ColorScheme,
        sizeClass: UserInterfaceSizeClass?
    ) -> AndroidResolvedStyle {
        let shadow = theme[keyPath: shadowKeyPath]
            .resolved(colorScheme: colorScheme, sizeClass: sizeClass)?
            .androidResolvedStyle.shadow
        return base.androidThemeRendering(theme: theme, colorScheme: colorScheme, sizeClass: sizeClass)
            .adding(shadow)
    }
}

// MARK: - Wrapper views

nonisolated public enum ThemeStyleTarget: Sendable {
    case foreground
    case background(ignoresSafeAreaEdges: Edge.Set)
    case border(width: CGFloat)
}

nonisolated struct ThemeStyledView<Content: View, Style: AndroidShapeStyleAdapter>: View {

    @Environment(\.theme) var theme: Theme
    @Environment(\.colorScheme) var colorScheme: ColorScheme
    @Environment(\.horizontalSizeClass) var sizeClass: UserInterfaceSizeClass?

    let style: Style
    let target: ThemeStyleTarget
    let content: Content

    var body: some View {
        let rendering = style.androidThemeRendering(
            theme: theme, colorScheme: colorScheme, sizeClass: sizeClass
        )
        styled(rendering).androidThemeShadow(rendering.shadow)
    }

    @ViewBuilder
    private func styled(_ rendering: AndroidResolvedStyle) -> some View {
        if let shapeStyle = rendering.shapeStyle {
            switch target {
            case .foreground:
                content.foregroundStyle(shapeStyle)
            case .background(let edges):
                content.background(shapeStyle, ignoresSafeAreaEdges: edges)
            case .border(let width):
                content.border(shapeStyle, width: width)
            }
        } else {
            content
        }
    }
}

nonisolated struct ThemeBackgroundShapeView<Content: View, Style: AndroidShapeStyleAdapter, ShapeType: Shape>: View {

    @Environment(\.theme) var theme: Theme
    @Environment(\.colorScheme) var colorScheme: ColorScheme
    @Environment(\.horizontalSizeClass) var sizeClass: UserInterfaceSizeClass?

    let style: Style
    let shape: ShapeType
    let fillStyle: FillStyle
    let content: Content

    var body: some View {
        let rendering = style.androidThemeRendering(
            theme: theme, colorScheme: colorScheme, sizeClass: sizeClass
        )
        if let shapeStyle = rendering.shapeStyle {
            content.background {
                shape.fill(shapeStyle, style: fillStyle)
                    .androidThemeShadow(rendering.shadow)
            }
        } else {
            content.androidThemeShadow(rendering.shadow)
        }
    }
}

nonisolated public enum ThemeShapeTarget: Sendable {
    case fill(FillStyle)
    case stroke(lineWidth: CGFloat)
}

nonisolated struct ThemeStyledShapeView<ShapeType: Shape, Style: AndroidShapeStyleAdapter>: View {

    @Environment(\.theme) var theme: Theme
    @Environment(\.colorScheme) var colorScheme: ColorScheme
    @Environment(\.horizontalSizeClass) var sizeClass: UserInterfaceSizeClass?

    let shape: ShapeType
    let style: Style
    let target: ThemeShapeTarget

    var body: some View {
        let rendering = style.androidThemeRendering(
            theme: theme, colorScheme: colorScheme, sizeClass: sizeClass
        )
        filled(rendering).androidThemeShadow(rendering.shadow)
    }

    @ViewBuilder
    private func filled(_ rendering: AndroidResolvedStyle) -> some View {
        if let shapeStyle = rendering.shapeStyle {
            switch target {
            case .fill(let fillStyle):
                shape.fill(shapeStyle, style: fillStyle)
            case .stroke(let lineWidth):
                shape.stroke(shapeStyle, lineWidth: lineWidth)
            }
        } else {
            shape.fill(Color.clear)
        }
    }
}

// MARK: - Modifier overloads

nonisolated extension View {

    nonisolated public func foregroundStyle<S: AndroidShapeStyleAdapter>(_ style: S) -> some View {
        ThemeStyledView(style: style, target: .foreground, content: self)
    }

    nonisolated public func background<S: AndroidShapeStyleAdapter>(
        _ style: S,
        ignoresSafeAreaEdges edges: Edge.Set = []
    ) -> some View {
        ThemeStyledView(style: style, target: .background(ignoresSafeAreaEdges: edges), content: self)
    }

    nonisolated public func background<S: AndroidShapeStyleAdapter, T: Shape>(
        _ style: S,
        in shape: T,
        fillStyle: FillStyle = FillStyle()
    ) -> some View {
        ThemeBackgroundShapeView(style: style, shape: shape, fillStyle: fillStyle, content: self)
    }

    nonisolated public func border<S: AndroidShapeStyleAdapter>(
        _ style: S,
        width: CGFloat = 1
    ) -> some View {
        ThemeStyledView(style: style, target: .border(width: width), content: self)
    }
}

nonisolated extension Shape {

    nonisolated public func fill<S: AndroidShapeStyleAdapter>(
        _ style: S,
        style fillStyle: FillStyle = FillStyle()
    ) -> some View {
        ThemeStyledShapeView(shape: self, style: style, target: .fill(fillStyle))
    }

    nonisolated public func stroke<S: AndroidShapeStyleAdapter>(
        _ style: S,
        lineWidth: CGFloat = 1
    ) -> some View {
        ThemeStyledShapeView(shape: self, style: style, target: .stroke(lineWidth: lineWidth))
    }
}

#endif
